Repository US-EPA-CAMD/easey-ui, pull requests merged in 2020-10, with the labels that each got.

#295 Feature/228 Facilities Service Scaffolding
  .gitignore
  starter-kit/README.md
  starter-kit/docker-compose.yml
  starter-kit/facilities-api/.env
  starter-kit/facilities-api/.eslintrc.js
  starter-kit/facilities-api/.prettierrc
  starter-kit/facilities-api/Dockerfile.dev
  starter-kit/facilities-api/README.md
  starter-kit/facilities-api/nest-cli.json
  starter-kit/facilities-api/package-lock.json
  starter-kit/facilities-api/package.json
  starter-kit/facilities-api/src/app.controller.spec.ts
  starter-kit/facilities-api/src/app.controller.ts
  starter-kit/facilities-api/src/app.module.ts
  starter-kit/facilities-api/src/app.service.ts
  starter-kit/facilities-api/src/facilities/facilities.controller.ts
  starter-kit/facilities-api/src/facilities/facilities.module.ts
  starter-kit/facilities-api/src/facilities/facilities.service.ts
  starter-kit/facilities-api/src/main.ts
  starter-kit/facilities-api/test/app.e2e-spec.ts
  starter-kit/facilities-api/test/jest-e2e.json
  starter-kit/facilities-api/tsconfig.build.json
  starter-kit/facilities-api/tsconfig.json
  starter-kit/manifest.yml
  starter-kit/scripts/build.sh
Labels: Datateers

#296 Update build.sh
  starter-kit/scripts/build.sh
Labels: DevOps, Tech Team

#304 Feature/286 reusable tab component
  starter-kit/app/src/components/Common/Tabs/TabPane.js
  starter-kit/app/src/components/Common/Tabs/Tabs.js
  starter-kit/app/src/components/Common/Tabs/Tabs.test.js
Labels: Emissioners

#306 feature/293-local-db-table-creation-scripts
  starter-kit/db/1-initialize.sql
  starter-kit/db/2-camdmd-tables.sql
  starter-kit/db/3-camd-tables.sql
  starter-kit/db/4-camdecmpsmd-tables.sql
  starter-kit/db/5-camdecmps-tables.sql
  starter-kit/docker-compose.yml
Labels: Tech Team

#303 Feature/229 create facilities controller
  starter-kit/README.md
  starter-kit/facilities-api/README.md
  starter-kit/facilities-api/package-lock.json
  starter-kit/facilities-api/package.json
  starter-kit/facilities-api/src/app.controller.spec.ts
  starter-kit/facilities-api/src/app.controller.ts
  starter-kit/facilities-api/src/app.module.ts
  starter-kit/facilities-api/src/app.service.ts
  starter-kit/facilities-api/src/facilities/facilities.controller.ts
  starter-kit/facilities-api/src/facilities/facilities.service.ts
  starter-kit/facilities-api/src/main.ts
Labels: Datateers

#308 Docker Compose & Deploy fix
  starter-kit/docker-compose.yml
  starter-kit/scripts/build.sh
Labels: Tech Team

#310 feature/facilities-api-port-config
  starter-kit/facilities-api/src/main.ts
Labels: Datateers

#311 feature/fix-facility-api-deployment
  starter-kit/facilities-api/nest-cli.json
  starter-kit/facilities-api/package.json
  starter-kit/facilities-api/src/app.module.ts
  starter-kit/facilities-api/src/config/typeorm.config.ts
  starter-kit/facilities-api/src/facilities/facilities.module.ts
  starter-kit/tasks-api/src/config/config.service.ts
Labels: Tech Team

#309 feature/127-pagination
  starter-kit/app/package-lock.json
  starter-kit/app/package.json
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/TablePagination/TablePagination.css
  starter-kit/app/src/components/Common/Table/TablePagination/TablePagination.js
  starter-kit/app/src/components/Common/Table/TablePagination/TablePagination.test.js
  starter-kit/app/src/components/Common/Table/TablePaginationFilter/TablePaginationFilter.css
  starter-kit/app/src/components/Common/Table/TablePaginationFilter/TablePaginationFilter.js
  starter-kit/app/src/components/Common/Table/TableSearch/TableSearch.js
  starter-kit/app/src/components/Common/Table/UswdsTable.css
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Common/Table/UswdsTable.test.js
  starter-kit/app/src/components/Home/HomeView.css
  starter-kit/app/src/components/Home/HomeView.js
Labels: Emissioners

#325 Feature/284 home page layout
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/TablePagination/TablePagination.css
  starter-kit/app/src/components/Common/Table/UswdsTable.css
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Facilities/DataTable.js
  starter-kit/app/src/components/Facilities/DataTable.test.js
  starter-kit/app/src/components/Facilities/DataTableRender.css
  starter-kit/app/src/components/Facilities/DataTableRender.js
  starter-kit/app/src/components/Facilities/DataTableRender.test.js
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Home/Home.css
  starter-kit/app/src/components/Home/Home.js
  starter-kit/app/src/components/Home/HomeOverview.css
  starter-kit/app/src/components/Home/HomeOverview.js
  starter-kit/app/src/components/Home/HomeOverview.test.js
  starter-kit/app/src/components/Home/HomeTitle.css
  starter-kit/app/src/components/Home/HomeTitle.js
  starter-kit/app/src/components/Home/HomeTitle.test.js
  starter-kit/app/src/components/Home/HomeView.css
  starter-kit/app/src/components/Home/HomeView.js
  starter-kit/app/src/store/actions/facilities.js
  starter-kit/app/src/store/actions/facilities.test.js
Labels: Emissioners

#317 Feature/300 model grouping units entities
  starter-kit/facilities-api/src/config/typeorm.config.ts
  starter-kit/facilities-api/src/facilities/entities/unit-boiler-type.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-capacity.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-control.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-fuel.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-generator.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-op-status.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit-program.entity.ts
  starter-kit/facilities-api/src/facilities/entities/unit.entity.ts
Labels: Datateers

#326 Feature/298 create facility and location entities
  starter-kit/facilities-api/src/facilities/entities/plant.entity.ts
Labels: Datateers

#342 Feature/131 develop units tab table
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Facilities/DataTable.js
  starter-kit/app/src/components/Facilities/DataTableRender.js
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Facilities/Units/UnitsDataTable.js
  starter-kit/app/src/components/Facilities/Units/UnitsDataTable.test.js
  starter-kit/app/src/components/Facilities/Units/UnitsTableRender.css
  starter-kit/app/src/components/Facilities/Units/UnitsTableRender.js
  starter-kit/app/src/components/Home/Home.js
  starter-kit/app/src/utils/selectors/facilities.js
  starter-kit/app/src/utils/selectors/facilities.test.js
Labels: Emissioners

#343 Feature/130 monitoring plan
  starter-kit/app/src/components/Common/Table/TableBody.css
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Facilities/DataTable.js
  starter-kit/app/src/components/Facilities/DataTableRender.js
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Facilities/MonitoringPlan/MonitoringPlanDataTable.js
  starter-kit/app/src/components/Facilities/MonitoringPlan/MonitoringPlanDataTable.test.js
  starter-kit/app/src/components/Facilities/MonitoringPlan/MonitoringPlanTableRender.css
  starter-kit/app/src/components/Facilities/MonitoringPlan/MonitoringPlanTableRender.js
  starter-kit/app/src/components/Home/Home.js
Labels: Emissioners

#353 Feature/283 unit tab detailed view
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Facilities/Units/UnitDetailView.js
  starter-kit/app/src/components/Facilities/Units/Units.js
  starter-kit/app/src/components/Facilities/Units/Units.test.js
  starter-kit/app/src/components/Facilities/Units/UnitsDataTable.test.js
  starter-kit/app/src/components/Facilities/Units/UnitsTableRender.js
  starter-kit/app/src/utils/selectors/facilities.js
Labels: Emissioners

#357 Feature/132 contacts
  starter-kit/app/src/components/Facilities/Contacts/ContactsCard.css
  starter-kit/app/src/components/Facilities/Contacts/ContactsCard.js
  starter-kit/app/src/components/Facilities/Contacts/ContactsData.js
  starter-kit/app/src/components/Facilities/Contacts/ContactsData.test.js
  starter-kit/app/src/components/Facilities/Contacts/ContactsRender.css
  starter-kit/app/src/components/Facilities/Contacts/ContactsRender.js
  starter-kit/app/src/components/Facilities/Contacts/ContactsRoleCard.css
  starter-kit/app/src/components/Facilities/Contacts/ContactsRoleCard.js
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Facilities/MonitoringPlan/MonitoringPlanDataTable.test.js
  starter-kit/app/src/utils/selectors/facilities.js
Labels: Emissioners

#360 Feature/133 develop location tab
  starter-kit/app/public/index.html
  starter-kit/app/src/components/Facilities/DetailTabs.js
  starter-kit/app/src/components/Facilities/Location/Location.css
  starter-kit/app/src/components/Facilities/Location/Location.js
  starter-kit/app/src/components/Facilities/Location/Location.test.js
  starter-kit/app/src/components/Facilities/Location/LocationView.js
  starter-kit/app/src/components/Home/Home.js
Labels: Emissioners

#363 Feature/no data search
  starter-kit/app/src/components/Common/Table/TableBody.css
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Facilities/Contacts/ContactsRender.js
Labels: Emissioners

#355 Feature/issue 240 GitHub scanning
  .github/workflows/codeql-analysis.yml
Labels: Tech Team
