Repository US-EPA-CAMD/easey-ui, pull requests merged in 2020-11, with the labels that each got.

#376 License and contributing files for PI-1 repo
  CONTRIBUTING.md
  LICENSE.md
Labels: Tech Team

#439 Feature/386 editable table
  starter-kit/app/src/components/Common/Table/TableBody.css
  starter-kit/app/src/components/Common/Table/TableBody.js
  starter-kit/app/src/components/Common/Table/TableCell.js
  starter-kit/app/src/components/Common/Table/UswdsTable.js
  starter-kit/app/src/components/Facilities/DataTableRender.js
Labels: Emissioners

#377 feature/90-sonar-cloud-rules
  .github/workflows/pipeline-trigger-on-feature-branch.yml
  .github/workflows/pipeline-trigger-on-tag-develop-branch.yml
  sonar-project.properties
  starter-kit/app/src/App.css
  starter-kit/app/src/App.js
  starter-kit/app/src/App.test.js
  starter-kit/app/src/components/Common/Footer/Footer.test.js
  starter-kit/app/src/components/Common/Header/Header.test.js
Labels: Tech Team

#448 fixed failing unit tests
  .gitignore
  src/components/Common/Table/TablePaginationFilter/TablePaginationFilter.js
  src/components/Common/Table/TablePaginationFilter/TablePaginationFilter.test.js
  src/components/Common/Table/UswdsTable.test.js
Labels: Emissioners

#471 feature/316-test-env-setup-easey-ui
  manifest.dev.yml
  manifest.staging.yml
  manifest.test.yml
Labels: DevOps, Tech Team

#472 release/v0.0-easey-ui
  manifest.dev.yml
  manifest.staging.yml
  manifest.test.yml
Labels: DevOps, Tech Team

#474 release/v0.0-easey-ui
  manifest.dev.yml
  manifest.staging.yml
  manifest.test.yml
Labels: DevOps, Tech Team
