Repository US-EPA-CAMD/easey-ui, pull requests merged in 2020-08, with the labels that each got.

#94 Features/94 add sample unit tests
  .gitignore
  starter-kit/tasks-api/src/tasks/task.repository.spec.ts
  starter-kit/tasks-api/src/tasks/task.repository.ts
  starter-kit/tasks-api/src/tasks/tasks.service.spec.ts
Labels: Datateers

#104 features/68-manifest-config
  starter-kit/app/.env.local
  starter-kit/app/README.md
  starter-kit/app/package.json
  starter-kit/app/src/config.js
  starter-kit/app/src/store/actions/posts.js
  starter-kit/app/src/store/actions/tasks.js
  starter-kit/docker-compose.yml
  starter-kit/manifest.yml
  starter-kit/posts-api/config.js
  starter-kit/posts-api/package-lock.json
  starter-kit/posts-api/package.json
  starter-kit/posts-api/repositories/db.js
  starter-kit/tasks-api/.env
  starter-kit/tasks-api/package-lock.json
  starter-kit/tasks-api/package.json
  starter-kit/tasks-api/src/config/typeorm.config.ts
Labels: Datateers, DevOps

#105 features/69-add-github-workflow
  starter-kit/.github/workflows/main.yml
  starter-kit/app/src/config.js
Labels: Datateers, DevOps

#107 features/106-move-github-workflow-to-root
  .github/workflows/main.yml
Labels: Datateers, DevOps

#110 features/67-70-gulp-pipeline-to-handle-uswds-assets-and-updated-package-dependencies
  starter-kit/app/Dockerfile.dev
  starter-kit/app/gulpfile.js
  starter-kit/app/package.json
  starter-kit/app/src/components/Home/Home.js
  starter-kit/app/src/index.js
  starter-kit/app/src/uswds_assets/css/styles.css
  starter-kit/app/src/uswds_assets/css/styles.css.map
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-color.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-components.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-custom-styles.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-general.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-spacing.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-typography.scss
  starter-kit/app/src/uswds_assets/sass/_uswds-theme-utilities.scss
  starter-kit/app/src/uswds_assets/sass/styles.scss
Labels: Emissioners

#119 feature/118-update-github-workflow
  .github/workflows/main.yml
Labels: DevOps, Tech Team
