Repository US-EPA-CAMD/easey-ui, pull requests merged in 2021-04, with the labels that each got.

#1061 Feature/961 details
  package-lock.json
  package.json
  src/components/Common/Modal/Modal.css
  src/components/Common/Modal/Modal.js
  src/components/Common/Modal/Modal.test.js
  src/components/Common/Table/TableBody.js
  src/components/Common/Table/TablePaginationFilter/TablePaginationFilter.css
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/HeaderInfo/SelectBox/SelectBox.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/DataTableSystems.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/DataTableSystemsRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/DataTableSystemsRender.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.css
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/SelectBox/SelectBox.css
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/SelectBox/SelectBox.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/SelectBox/SelectBox.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/SystemDescriptions.js
  src/uswds_assets/css/styles.css
  src/uswds_assets/css/styles.css.map
Labels: Emissioners

#1092 Feature/962 system comp
  src/components/Common/Footer/Menu/Menu.js
  src/components/Common/Layout.js
  src/components/Common/LeftNavigation/Accessories/Accessories.js
  src/components/Common/Modal/Modal.css
  src/components/Common/Modal/Modal.test.js
  src/components/Common/NotFound/NotFound.js
  src/components/Common/Table/TableBody.css
  src/components/Common/Table/TableBody.js
  src/components/Common/Table/TableHeader.js
  src/components/Common/Table/UswdsTable.css
  src/components/Common/Table/UswdsTable.js
  src/components/Common/Table/UswdsTable.test.js
  src/components/Common/Tabs/Tabs.js
  src/components/Common/WideHeader/WideHeader.css
  src/components/Common/WideHeader/WideHeader.js
  src/components/Facilities/Contacts/ContactsData.js
  src/components/Facilities/Contacts/ContactsRoleCard.js
  src/components/Facilities/DataTableRender.js
  src/components/Facilities/MonitoringPlan/MonitoringPlanTableRender.js
  src/components/Facilities/Units/UnitsTableRender.js
  src/components/Home/Home.js
  src/components/Home/HomeOverview.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/HeaderInfo/SelectBox/SelectBox.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/MonitoringPlanTab.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/MonitoringPlanTabRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/MATS/DataTableMatsRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Methods/DataTableMethodRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/DataTableSystems.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/DataTableSystemsRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.css
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/SystemsComponent/DataTableSystemsComponents.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/SystemsComponent/DataTableSystemsComponents.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/SystemsComponent/DataTableSystemsComponentsRender.css
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/SystemsComponent/DataTableSystemsComponentsRender.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/SystemsComponent/DataTableSystemsComponentsRender.test.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Tables/Tables.js
  src/components/MonitoringPlans/DynamicTabBar/SelectFacilitiesTab/DataTableRender.js
  src/store/actions/actionTypes.js
  src/store/actions/apiStatusActions.js
  src/store/actions/monitoringSystems.js
  src/store/actions/monitoringSystems.test.js
  src/store/reducers/apiStatusReducer.js
  src/store/reducers/apiStatusReducer.test.js
  src/store/reducers/initialState.js
  src/store/reducers/monitoringSystems.js
  src/store/reducers/monitoringSystems.test.js
  src/uswds_assets/css/styles.css
  src/utils/api/monitoringPlansApi.js
  src/utils/selectors/monitoringPlanSystems.js
  src/utils/selectors/monitoringPlanSystems.test.js
Labels: Emissioners

#1097 feature/initial-bre-rule-authoring-ui-design
  public/assets/css/codeeffects/black.css
  public/assets/css/codeeffects/blue.css
  public/assets/css/codeeffects/common.css
  public/assets/css/codeeffects/gray.css
  public/assets/css/codeeffects/green.css
  public/assets/css/codeeffects/navy.css
  public/assets/css/codeeffects/red.css
  public/assets/css/codeeffects/white.css
  public/assets/js/codeeffects/editor.js
  public/index.html
  src/App.js
  src/components/RuleEditor/RuleEditor.css
  src/components/RuleEditor/RuleEditor.js
  src/config.js
  [B[B[B[A
Labels: Tech Team

#1270 508 updates datatable
  src/components/Common/Table/TableBody.js
  src/components/Common/Table/TableBody.test.js
  src/components/Common/Table/TableHeader.js
  src/components/Common/Table/TablePagination/TablePagination.js
  src/components/Common/Table/TablePagination/TablePagination.test.js
  src/components/Common/Table/UswdsTable.js
  src/components/Common/Table/UswdsTable.test.js
  src/components/Common/WideHeader/Menu/Menu.js
  src/components/Home/Home.test.js
  src/components/Home/HomeOverview.js
  src/components/Home/HomeTitle.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/HeaderInfo/HeaderInfo.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/HeaderInfo/SelectBox/SelectBox.js
  src/components/MonitoringPlans/DynamicTabBar/MonitoringPlanTab/Sections/Systems/Details/Details.js
  src/utils/selectors/monitoringPlanSystems.test.js
Labels: Emissioners

#1297 508 updated
  package-lock.json
  src/components/Common/Table/TableBody.test.js
  src/components/DetailsSelectBox/DetailsSelectBox.test.js
  src/components/HeaderInfo/HeaderInfo.js
  src/components/MonitoringPlanTabRender/MonitoringPlanTabRender.js
  src/components/SelectBox/SelectBox.js
  src/components/SelectBox/SelectBox.test.js
  src/components/TableBody/TableBody.js
  src/components/TableBody/TableBody.test.js
  src/components/WideHeader/WideHeader.test.js
Labels: Emissioners

#1304 Feature/899 508 dropdown
  src/components/DetailsSelectBox/DetailsSelectBox.js
  src/components/SelectBox/SelectBox.js
Labels: Emissioners

#1306 Feature/899 508 dropdown
  src/components/DetailsSelectBox/DetailsSelectBox.js
  src/components/SelectBox/SelectBox.js
Labels: 508

#1307 Feature/899 508 dropdown
  src/components/SelectBox/SelectBox.js
Labels: 508

#1314 header
  src/components/DataTableSystemsComponents/DataTableSystemsComponents.js
  src/components/DataTableSystemsComponentsRender/DataTableSystemsComponentsRender.js
Labels: Emissioners
